# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-05 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('json_schema', jsonfield.fields.JSONField(blank=True)),
            ],
        ),
    ]
