FIELD_TYPE_NUMBER = 'number'
FIELD_TYPE_TEXT = 'text'
FIELD_TYPE_DATE = 'date'
FIELD_TYPE_ENUM = 'enum'
FIELD_TYPES = ((FIELD_TYPE_NUMBER, FIELD_TYPE_NUMBER),
               (FIELD_TYPE_TEXT, FIELD_TYPE_TEXT),
               (FIELD_TYPE_DATE, FIELD_TYPE_DATE),
               (FIELD_TYPE_ENUM, FIELD_TYPE_ENUM),)